services:
  postgres:
    image: postgres:16
    container_name: cs600-postgres
    environment:
      POSTGRES_DB: cs600db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - cs600-postgres-data:/var/lib/postgresql/data

volumes:
  cs600-postgres-data:
