services:
  postgres:
    image: postgres:16
    container_name: module5-postgres
    environment:
      POSTGRES_DB: module5db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - module5-postgres-data:/var/lib/postgresql/data

volumes:
  module5-postgres-data:
